---
- name: Clone_and_setup_VM
  hosts: "{{ esxi_host }}"
  gather_facts: no
  tasks:
    - name: Create destination directory for the cloned VM
      file:
        path: "{{ destination_path }}/{{ vm_name }}"
        state: directory
      tags: 
        - Clone_and_setup_VM
      delegate_to: "{{ inventory_hostname }}"

    - name: Clone VM disk from template
      shell: >
        vmkfstools -i "{{ template_vmdk_path }}"
        "{{ destination_path }}/{{ vm_name }}/{{ vm_name }}.vmdk" -d thin
      tags: 
        - Clone_and_setup_VM
      delegate_to: "{{ inventory_hostname }}"
      args:
        executable: /bin/sh

    - name: Copy VMX file to destination
      shell: >
        cp "{{ template_vmx_path }}"
        "{{ destination_path }}/{{ vm_name }}/{{ vm_name }}.vmx"
      tags: 
        - Clone_and_setup_VM
      delegate_to: "{{ inventory_hostname }}"
      args:
        executable: /bin/sh

    - name: Update VMX file for the cloned VM
      replace:
        path: "{{ destination_path }}/{{ vm_name }}/{{ vm_name }}.vmx"
        regexp: '{{ template_name }}'
        replace: "{{ vm_name }}"
      tags: 
        - Clone_and_setup_VM
      delegate_to: "{{ inventory_hostname }}"

    - name: Register the cloned VM
      shell: >
        vim-cmd solo/registervm "{{ destination_path }}/{{ vm_name }}/{{ vm_name }}.vmx"
      tags: 
        - Clone_and_setup_VM
      delegate_to: "{{ inventory_hostname }}"
      args:
        executable: /bin/sh
