vm_names:
- vm_name: cluster04-db01
  new_ips:
      - network: ens192
        ip : 192.168.3.115
      - network: ens224
        ip : 100.100.100.115
- vm_name: cluster04-db02
  new_ips:
      - network: ens192
        ip : 192.168.3.116
      - network: ens224
        ip : 100.100.100.116
        
esxi_host: esxi-host
template_name: rac_template1
template_vmx: rac_template1.vmx
template_vmdks:
  - rac_template1_1.vmdk
  - rac_template1_2.vmdk
base_destination_path: /vmfs/volumes/datastore2_sas1
template_ip: 192.168.3.52
